name: build
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.9
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      - run: yarn coverage
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          base-path: packages/evm
